[ts] Fix `Dictionary<TEnum, V>.Clear()`.
    error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Partial<Record<...