[cs] Fix casting of `~C` to `byte` and `ushort`.
    error CS0221: Constant value '-241' cannot be converted to a 'byte' (use 'unchecked' syntax to override)

Fix #238